<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>
<body>
  <script>
    /*
      ## 基本用法
      ES6规定，`Promise`对象是一个构造函数，用来生成`Promise`实例。

      看下面的代码。
      ```js
      const promise = new Promise((resolve, reject) => {
        // 当作例子
        let bool = true;

        if (bool) {
          resolve(bool);
        } else {
          reject("失败");
        }
      });

      promise.then(res => console.log(res)); // true
      ```
      `Promise`构造函数接受一个函数作为参数，该函数的两个参数分别是`resolve`和`reject`。它们是两个函数。

      `resolve`函数的作用是，把`Promise`对象的状态从“未完成”变成“成功”，在异步操作成功时调用，并且把异步操作结果，当作参数传递出去；
      `reject`函数的作用时，把`Promise`对象的状态从“未完成”变成“失败”，在异步操作失败时调用，并且把异步操作报的错，当作参数传递出去；

      `Promise`实例生成以后，可以用`then`方法分别指定`resolved`状态和`rejected`状态的回调函数。
      ```js
      const promise = new Promise((resolve, reject) => {
        // 当作例子
        let bool = false;

        if (bool) {
          resolve(bool);
        } else {
          reject("失败");
        }
      });

      promise.then((res) => {
        console.log(res, "异步成功");
      }, (err) => {
        console.log(err, "异步失败");
        // 失败 异步失败
      });
      ```
      `then`方法接受两个回调函数作为参数。第一个回调函数就是`Promise`对象的状态变为`resolved`时调用，第二个回调函数是`Promise`对象状态
      为`rejected`时调用。第二个函数是可选的，也不一定需要选择第二个函数。这两个函数都接受`Promise`对象传出的值作为参数。

      看下面的例子：
      ```js
      function timeout(ms) {
        return new Promise((resolve, reject) => {
          setTimeout(resolve, ms, 'done');
        });
      }

      timeout(100).then((value) => {
        console.log(value);
      });
      ```
      上面的代码中，`timeout`方法返回一个`Promise`实例，表示一段时间才会发生的结果。过了指定的时间（`ms`参数）以后，`Promise`实例的状态
      变为`resolved`，就会触发`then`方法绑定的回调函数。

      `Promise`新建后就会立即执行。
      ```js
      let promise = new Promise((resolve, reject) => {
        console.log('Promise');
        resolve();
      });

      promise.then(() => {
        console.log('resolved.');
      });

      console.log('Hi!');
      // Promise
      // Hi!
      // resolved.
      ```
      上面的代码中，`Promise`新建后立即执行，所以输出的是`Promise`。然后，`then`方法指定的回调函数，将在当前脚本所有同步的代码执行完才会执行，
      所以`resolved`最后输出。

      下面是异步加载图片的例子。
      ```js
      function loadImageAsync(url) {
        return new Promise((resolve, reject) => {
          const image = new Image();

          image.onload = function() {
            resolve(image);
          };

          image.onerror = function() {
            reject(new Error('Could not load image at ' + url));
          }

          image.src = url;
        })
      }
      ```
      上面的代码种，使用`Promise`包装了一个图片加载的异步操作。如果加载成功。就调用`resolve`方法，否则调用`reject`方法。

      下面是一个用`Promise`对象实现的Ajax操作的例子。
      ```js
      const ajax = function(url) {
        const promise = new Promise((resolve, reject) => {
          const handler = function() {
            if (this.readyState !== 4) {
              return;
            }

            if (this.status === 200) {
              resolve(this.response);
            } else {
              reject(new Error(this.statusText));
            }
          }

          const xhr = new XMLHttpRequest();

          xhr.open("GET", url);
          xhr.onreadystatechange = handler;
          xhr.responseType = "json";
          xhr.setRequestHeader("Accept", "application/json");
          xhr.send();
        });
        
        return promise
      };

      ajax("/posts.json").then((res) => {
        console.log("调用成功", res);
      }, (err) => {
        console.log("调用失败", err);
      });
      ```
      上面代码中，`ajax`是对`XMLHttpRequest`对象的封装，用于发出一个针对`JSON`数据的`HTTP`请求，并且返回一个`Promise`对象。
      但要注意的是，在`ajax`内部，`resolve`函数和`reject`函数调用时，都会带有参数。

      如果调用`resolve`函数和`reject`函数带有参数的话，它们的参数会被传递给回调函数。`reject`函数的参数一般是`Error`对象的实例，
      表示抛出错误；`resolve`函数的参数除了正常的值之外，还有可能是另一个Promise实例，看下面的例子：
      ```js
      const promise1 = new Promise((resolve, reject) => {
        // 做某些操作...
      });

      const promise2 = new Promise((resolve, reject) => {
        // 做某些操作...
      });
      ```
      这个例子中，`promise1`和`promise2`都是Promise的实例，但是`promise2`的`resolve`方法把`promise1`作为参数，也就是说，一个异步操作
      的结果是返回另一个异步操作。

      要注意的是，`promise1`的状态就传递给了`promise2`，也就是说，`promise1`的状态决定了`promise2`的状态。如果`promise1`的状态是进行中
      （`pending`），那`promise2`的回调函数就会等待`promise1`的状态改变；如果`promise`的状态已经是`resolved`或者`rejected`，那`promise2`
      的回调函数就会立马执行。
      ```js
      const promise1 = new Promise((resolve, reject) => {
        setTimeout(() => reject(new Error('fail')), 3000);
      });

      const promise2 = new Promise((resolve, reject) => {
        setTimeout(() => resolve(promise1), 1000);
      });

      promise2
        .then(res => {
          console.log("调用成功", res);
        })
        .catch(err => {
          console.log("调用失败", err);
          // 调用失败 Error: fail
        });
      ```
      上面的代码中，`promise1`是一个Promise，3秒后变成`rejected`。`promise2`的状态在1秒之后改变，`resolve`方法返回的是`promise1`。
      由于`promise2`返回的是另一个Promise，就导致`promise2`自己的状态无效了。是由`promise1`的状态来决定`promise2`的状态。所以，后面
      的`then`语句就变成针对`promise1`。又过了2秒，`promise1`变成了`rejected`，就导致触发`catch`方法指定的回调函数。

      要注意的是，调用`resolve`或`reject`并不会结束Promise的参数函数执行。
      ```js
      new Promise((resolve, reject) => {
        resolve(1);
        console.log(2);
      }).then(res => {
        console.log(res);
      });
      // 2
      // 1
      ```
      上面的代码中，调用`resolve(1)`后，后面的`console.log(2)`还会执行，并且是首先在控制台输出。这是因为立即resolved的Promise是在本
      轮的事件循环的最后才执行的，总会在本轮循环的同步任务之后才执行。

      为了避免一些意外，调用`resolve`或`reject`之后，Promise也就完成了，后面的操作应该放到`then`方法里面，而不是写在`resolve`或`reject`
      后面。
      ```js
      new Promise((resolve, reject) => {
        return resolve();

        // return之后的代码都不会执行
        console.log("打印某些东西");
      });
      ```
    */
    
  </script>
</body>
</html>